name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm i && npm run build

      - name: Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: template-config.yml
          upload_url: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
